Models/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;
namespace AspWrong.Models
{
    public class RegisterViewModel
    {
        [Required]
        [EmailAddress(ErrorMessage = "Neplatná emailová adresa")]
        [Display(Name = "Email")]
        public string Email { get; set; } = "";

        [Required]
        [StringLength(100, ErrorMessage = "{0} musí mít délku alespoň {2} a nejvíc {1} znaků.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Heslo")]
        public string Password { get; set; } = "";

        [DataType(DataType.Password)]
        [Display(Name = "Potvrzení hesla")]
        [Compare("Password", ErrorMessage = "Zadaná hesla se musí shodovat.")]
        public string ConfirmPassword { get; set; } = "";
    }
}

Controllers/Article1Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AspWrong.Data;
using AspWrong.Models;
using Microsoft.AspNetCore.Authorization;
using PagedList;

namespace AspBlog.Controllers
{
    [Authorize(Roles="admin")]
    public class Article1Controller : Controller
    {
        private readonly ApplicationDbContext _context;

        public Article1Controller(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Article1
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
              return _context.Article1 != null ? 
                          View(await _context.Article1.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Article1'  is null.");
        }

        // Get Search
        public async Task<IActionResult> Vyhledat(string SearchString)
        {
            //if (_context.Article1 == null)
            // {
            //     return Problem("Entity set 'ApplicationDbContext.Article1'  is null.");
            //}
            ViewData["Vyhledat"] = SearchString;
            var article1 = from m in _context.Article1
                         select m;

            if (!String.IsNullOrEmpty(SearchString))
            {
                article1 = article1.Where(s => s.Příjmení!.Contains(SearchString));
            }

            return View(await article1.ToListAsync());
        }

        // GET: Article1/Details/5

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Article1 == null)
            {
                return NotFound();
            }

            var article1 = await _context.Article1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article1 == null)
            {
                return NotFound();
            }

            return View(article1);
        }

        // GET: Article1/Create
        [AllowAnonymous]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Article1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create([Bind("Id,Jméno,Příjmení,Adresa,Obec,PSČ,Telefon,Email")] Article1 article1)
        {
            if (ModelState.IsValid)
            {
                _context.Add(article1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Ulozit));
            }
            return View(article1);
        }

        // GET: Article1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Article1 == null)
            {
                return NotFound();
            }

            var article1 = await _context.Article1.FindAsync(id);
            if (article1 == null)
            {
                return NotFound();
            }
            return View(article1);
        }

        // POST: Article1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Jméno,Příjmení,Adresa,Obec,PSČ,Telefon,Email")] Article1 article1)
        {
            if (id != article1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Article1Exists(article1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article1);
        }

        // GET: Article1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Article1 == null)
            {
                return NotFound();
            }

            var article1 = await _context.Article1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article1 == null)
            {
                return NotFound();
            }

            return View(article1);
        }

        // POST: Article1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Article1 == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Article1'  is null.");
            }
            var article1 = await _context.Article1.FindAsync(id);
            if (article1 != null)
            {
                _context.Article1.Remove(article1);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Article1Exists(int id)
        {
          return (_context.Article1?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        [HttpPost]
        public string Vyhledat(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }
        public IActionResult Ulozit()
        {
            return View();
        }
    }
}

Controllers/Article2Controller.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using AspWrong.Data;
using AspWrong.Models;
using PagedList;

namespace AspWrong.Controllers
{
    public class Article2Controller : Controller
    {
        private readonly ApplicationDbContext _context;

        public Article2Controller(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Article2
        public async Task<IActionResult> Index()
        {
              return _context.Article2 != null ? 
                          View(await _context.Article2.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Article2'  is null.");
        }
        // Get Search
        public async Task<IActionResult> Vyhledat(string SearchString)
        {
            //if (_context.Article2 == null)
            //{
            //    return Problem("Entity set 'ApplicationDbContext.Article2'  is null.");
            //}
            ViewData["Vyhledat"] = SearchString;
            var article2 = from m in _context.Article2
                           select m;

            if (!String.IsNullOrEmpty(SearchString))
            {
                article2 = article2.Where(s => s.Příjmení!.Contains(SearchString));
            }

            return View(await article2.ToListAsync());
        }
        // GET: Article2/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Article2 == null)
            {
                return NotFound();
            }

            var article2 = await _context.Article2
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article2 == null)
            {
                return NotFound();
            }

            return View(article2);
        }

        // GET: Article2/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Article2/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Jméno,Příjmení,Popis")] Article2 article2)
        {
            if (ModelState.IsValid)
            {
                _context.Add(article2);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Ulozit));
            }
            return View(article2);
        }

        // GET: Article2/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Article2 == null)
            {
                return NotFound();
            }

            var article2 = await _context.Article2.FindAsync(id);
            if (article2 == null)
            {
                return NotFound();
            }
            return View(article2);
        }

        // POST: Article2/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Jméno,Příjmení,Popis")] Article2 article2)
        {
            if (id != article2.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Article2Exists(article2.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(article2);
        }

        // GET: Article2/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Article2 == null)
            {
                return NotFound();
            }

            var article2 = await _context.Article2
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article2 == null)
            {
                return NotFound();
            }

            return View(article2);
        }

        // POST: Article2/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Article2 == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Article2'  is null.");
            }
            var article2 = await _context.Article2.FindAsync(id);
            if (article2 != null)
            {
                _context.Article2.Remove(article2);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Article2Exists(int id)
        {
          return (_context.Article2?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public IActionResult Ulozit()
        {
            return View();
        }
    }
}

Controllers/PojistkasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspWrong.Data;
using AspWrong.Models;
using PagedList;

namespace AspWrong.Controllers
{
    public class PojistkasController :Controller 
    {
        private readonly ApplicationDbContext _context;

        public PojistkasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pojistkas
        public async Task<IActionResult> Index()
        {
              return _context.Pojistka != null ? 
                          View(await _context.Pojistka.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Pojistka'  is null.");
        }

        // GET: Pojistkas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pojistka == null)
            {
                return NotFound();
            }

            var pojistka = await _context.Pojistka
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pojistka == null)
            {
                return NotFound();
            }

            return View(pojistka);
        }
        public async Task<IActionResult> Vyhledat(string SearchString)
        {
            //if (_context.Pojistkas == null)
            // {
            //     return Problem("Entity set 'ApplicationDbContext.Article1'  is null.");
            //}
            ViewData["Vyhledat"] = SearchString;
            var pojistka = from m in _context.Pojistka
                           select m;

            if (!String.IsNullOrEmpty(SearchString))
            {
                pojistka = pojistka.Where(s => s.Predmet!.Contains(SearchString));
            }

            return View(await pojistka.ToListAsync());
        }

        // GET: Pojistkas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pojistkas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PojistenyId,Majetek,Osoby,Zivot,Uraz,Predmet,Od,Do")] Pojistka pojistka)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pojistka);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Ulozit));
            }
            return View(pojistka);
        }

        // GET: Pojistkas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pojistka == null)
            {
                return NotFound();
            }

            var pojistka = await _context.Pojistka.FindAsync(id);
            if (pojistka == null)
            {
                return NotFound();
            }
            return View(pojistka);
        }

        // POST: Pojistkas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PojistenyId,Majetek,Osoby,Zivot,Uraz,Predmet,Od,Do")] Pojistka pojistka)
        {
            if (id != pojistka.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pojistka);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PojistkaExists(pojistka.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pojistka);
        }

        // GET: Pojistkas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pojistka == null)
            {
                return NotFound();
            }

            var pojistka = await _context.Pojistka
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pojistka == null)
            {
                return NotFound();
            }

            return View(pojistka);
        }

        // POST: Pojistkas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pojistka == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pojistka'  is null.");
            }
            var pojistka = await _context.Pojistka.FindAsync(id);
            if (pojistka != null)
            {
                _context.Pojistka.Remove(pojistka);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PojistkaExists(int id)
        {
          return (_context.Pojistka?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public IActionResult Ulozit()
        {
            return View();
        }
    }
}

Views/Home/Contact.cshtml
@using Microsoft.AspNetCore.Identity

@model LoginViewModel
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Přihlášení";
}

<section>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form class="d-flex flex-column gap-2" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label asp-for="RememberMe">
                            <input asp-for="RememberMe" />
                            @Html.DisplayNameFor(m => m.RememberMe)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="clanky-tlacitko align-self-start">Přihlásit se</button>
                </div>
                <div class="form-group">
                    <p>
                        <a asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]">Registrace</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</section>

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model RegisterViewModel
@{
    ViewData["Title"] = "Evidence";
}


<section>
        <img src="~/images/deposit.jpg" class="deposit"¨class="rounded-circle" class="float" alt="auto">
    <p>
        Vítejte v aplikaci Wrong.
    </p>
    <p>
        Aplikace byla vytvořena za účelem zlepšení komunikace mezi pojišťovnou a klienty. Kontaktovat nás můžete na 
        <a asp-controller="Home" asp-action="Kontakt">kontaktní stránce</a>.
    </p>
    <p>Aplikace umožňuje evidenci:</p>
    <ul>
        <li>Pojištěnců</li>
        <li>Pojistných událostí</li>
        <li>Pojištění</li>
    </ul>
    <p>
    </p>

    <p class="tlacitko-odstavec">
        <a asp-controller="Article1" asp-action="Create" class="reference-tlacitko">Vytvořit pojištění</a>
        <a asp-controller="Article2" asp-action="Create" class="reference-tlacitko">Nahlásit událost</a>
    </p>
    <a asp-controller="Account" asp-action="Login">Přihlásit se</a>
    <div class="cistic"></div>
</section>

Views/Home/Kontakt.cshtml
@{
    ViewData["Title"] = "Kontakt";
}

<section>
    <p>Aplikace byla založena roku 2023 proto, aby pomáhala budoucím klientům a klientům pojišťovny s jejich administrací.</p>
        <p>
            <img src="~/images/email.png" alt="email" class="vlevo" />
            Pokud nám chcete něco sdělit, využijte formuláře níže</strong>.
        </p>

        <p class="centrovany">
            <iframe frameborder="0" scrolling="no" width="500" height="220"
                    src="https://www.itnetwork.cz/service/mail_form.php?hash=5b5a8cdab989b5e4833544f23501910b">
            </iframe>
        </p>
    </section>

Views/Home/Pojisteni.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model RegisterViewModel
@{
    ViewData["Title"] = "Pojištění";
}
<section>
  <div>
        <strong>Vytvořit pojištění je možné níže:</strong>
  </div>
  <p>
    </p>
    <p class="tlacitko-odstavec"> 
        <a asp-controller="Article1" asp-action="Create" class="reference-tlacitko">Vytvořit pojištěného + pojištění</a>
       
        @if (User.IsInRole("admin"))
        {
        <a asp-controller="Article1" asp-action="Vyhledat" class="reference-tlacitko">Vyhledat pojištěného</a>
        <a asp-controller="Pojistkas" asp-action="Vyhledat" class="reference-tlacitko">Vyhledat pojištění</a>
            <a asp-controller="Article1" asp-action="Index" class="reference-tlacitko">Seznam pojištěnců</a>
        }
    </p>
    <div class="cistic"></div>
</section>

Views/Home/Prihlas.cshtml
@using Microsoft.AspNetCore.Identity

@model LoginViewModel
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Přihlášení";
}

<section>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form class="d-flex flex-column gap-2" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label asp-for="RememberMe">
                            <input asp-for="RememberMe" />
                            @Html.DisplayNameFor(m => m.RememberMe)
                        </label>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="clanky-tlacitko align-self-start">Přihlásit se</button>
                </div>
                <div class="form-group">
                    <p>
                        <a asp-action="Register" asp-route-returnurl="@ViewData["ReturnUrl"]">Registrace</a>
                    </p>
                </div>
            </form>
        </div>
    </div>
</section>

Views/Home/References.cshtml
@{
    ViewData["Title"] = "Kontakt";
}

<section>
    <p>Aplikace byla založena roku 2023 proto, aby pomáhala klientům pojišťovny a také budoucím klientům s jejich administrací.</p>
        <p>
            <img src="~/images/email.png" alt="email" class="vlevo" />
            Pokud nám chcete něco sdělit, využijte formuláře níže</strong>.
        </p>

        <p class="centrovany">
            <iframe frameborder="0" scrolling="no" width="500" height="220"
                    src="https://www.itnetwork.cz/service/mail_form.php?hash=5b5a8cdab989b5e4833544f23501910b">
            </iframe>
        </p>
    </section>

Views/Home/Register.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model RegisterViewModel
@inject SignInManager<IdentityUser> SignInManager
@{
    ViewData["Title"] = "Registrace";
}

<section>
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form class="d-flex flex-column gap-2" asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword"></label>
                    <input asp-for="ConfirmPassword" class="form-control" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
                <button type="submit" class="clanky-tlacitko align-self-start">Registrovat</button>
            </form>
        </div>
    </div>
</section>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

Views/Home/Udalosti.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<IdentityUser> UserManager
@model RegisterViewModel
@{
    ViewData["Title"] = "Evidence pojistné události";
}


<section>
   <strong>Přidat pojistnou událost můžete níže:</strong>
    </p>
    <p></p>

    <p class="tlacitko-odstavec">
        <a asp-controller="Article2" asp-action="Create" class="reference-tlacitko">Přidat pojistnou událost</a> 

        @if (User.IsInRole("admin"))
        {
            <a asp-controller="Article2" asp-action="Vyhledat" class="reference-tlacitko">Vyhledat pojistnou událost</a>
            <a asp-controller="Article2" asp-action="Index" class="reference-tlacitko">Seznam pojistných událostí</a>
        }
    </p>
    <div class="cistic"></div>
</section>